spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.4:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  application:
    name: order

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.3:8761/eureka/,http://192.168.1.3:8762/eureka/,http://192.168.1.3:8763/eureka/

server:
  port: 8081

#配置负载均衡的规则
#这个是ribbon的配置, 借助 Feign调用服务后, 配置失效
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule